#pragma once

#include <zcm/detail/vec4_access.hpp>

namespace zcm
{

    struct vec3;
    struct vec2;
    struct alignas(16) vec4
    {
        vec4 () noexcept;
        vec4 (float value) noexcept;
        vec4 (float x, float y, float z, float w) noexcept;

        vec4 (const vec3& xyz, float w) noexcept;
        vec4 (float x, const vec3& yzw) noexcept;

        vec4 (const vec2& xy, const vec2& zw) noexcept;
        vec4 (const vec2& xy, float z, float w) noexcept;
        vec4 (float x, const vec2& yz, float w) noexcept;
        vec4 (float x, float y, const vec2& zw) noexcept;

        float& operator[](unsigned val) noexcept;
        const float& operator[](unsigned val) const noexcept;

        void operator +=(const vec4& other) noexcept;
        void operator -=(const vec4& other) noexcept;
        void operator *=(const vec4& other) noexcept;
        void operator /=(const vec4& other) noexcept;

        void operator +=(float scalar) noexcept;
        void operator -=(float scalar) noexcept;
        void operator *=(float scalar) noexcept;
        void operator /=(float scalar) noexcept;

        union {
            float _data[4];

            detail::scalar_accessor_4<0> x;
            detail::scalar_accessor_4<1> y;
            detail::scalar_accessor_4<2> z;
            detail::scalar_accessor_4<3> w;

            detail::shuffle_accessor_4<vec2, 0, 0> xx;
            detail::shuffle_accessor_4<vec2, 1, 0> yx;
            detail::shuffle_accessor_4<vec2, 2, 0> zx;
            detail::shuffle_accessor_4<vec2, 3, 0> wx;
            detail::shuffle_accessor_4<vec2, 0, 1> xy;
            detail::shuffle_accessor_4<vec2, 1, 1> yy;
            detail::shuffle_accessor_4<vec2, 2, 1> zy;
            detail::shuffle_accessor_4<vec2, 3, 1> wy;
            detail::shuffle_accessor_4<vec2, 0, 2> xz;
            detail::shuffle_accessor_4<vec2, 1, 2> yz;
            detail::shuffle_accessor_4<vec2, 2, 2> zz;
            detail::shuffle_accessor_4<vec2, 3, 2> wz;
            detail::shuffle_accessor_4<vec2, 0, 3> xw;
            detail::shuffle_accessor_4<vec2, 1, 3> yw;
            detail::shuffle_accessor_4<vec2, 2, 3> zw;
            detail::shuffle_accessor_4<vec2, 3, 3> ww;

            detail::shuffle_accessor_4<vec3, 0, 0, 0> xxx;
            detail::shuffle_accessor_4<vec3, 1, 0, 0> yxx;
            detail::shuffle_accessor_4<vec3, 2, 0, 0> zxx;
            detail::shuffle_accessor_4<vec3, 3, 0, 0> wxx;
            detail::shuffle_accessor_4<vec3, 0, 1, 0> xyx;
            detail::shuffle_accessor_4<vec3, 1, 1, 0> yyx;
            detail::shuffle_accessor_4<vec3, 2, 1, 0> zyx;
            detail::shuffle_accessor_4<vec3, 3, 1, 0> wyx;
            detail::shuffle_accessor_4<vec3, 0, 2, 0> xzx;
            detail::shuffle_accessor_4<vec3, 1, 2, 0> yzx;
            detail::shuffle_accessor_4<vec3, 2, 2, 0> zzx;
            detail::shuffle_accessor_4<vec3, 3, 2, 0> wzx;
            detail::shuffle_accessor_4<vec3, 0, 3, 0> xwx;
            detail::shuffle_accessor_4<vec3, 1, 3, 0> ywx;
            detail::shuffle_accessor_4<vec3, 2, 3, 0> zwx;
            detail::shuffle_accessor_4<vec3, 3, 3, 0> wwx;
            detail::shuffle_accessor_4<vec3, 0, 0, 1> xxy;
            detail::shuffle_accessor_4<vec3, 1, 0, 1> yxy;
            detail::shuffle_accessor_4<vec3, 2, 0, 1> zxy;
            detail::shuffle_accessor_4<vec3, 3, 0, 1> wxy;
            detail::shuffle_accessor_4<vec3, 0, 1, 1> xyy;
            detail::shuffle_accessor_4<vec3, 1, 1, 1> yyy;
            detail::shuffle_accessor_4<vec3, 2, 1, 1> zyy;
            detail::shuffle_accessor_4<vec3, 3, 1, 1> wyy;
            detail::shuffle_accessor_4<vec3, 0, 2, 1> xzy;
            detail::shuffle_accessor_4<vec3, 1, 2, 1> yzy;
            detail::shuffle_accessor_4<vec3, 2, 2, 1> zzy;
            detail::shuffle_accessor_4<vec3, 3, 2, 1> wzy;
            detail::shuffle_accessor_4<vec3, 0, 3, 1> xwy;
            detail::shuffle_accessor_4<vec3, 1, 3, 1> ywy;
            detail::shuffle_accessor_4<vec3, 2, 3, 1> zwy;
            detail::shuffle_accessor_4<vec3, 3, 3, 1> wwy;
            detail::shuffle_accessor_4<vec3, 0, 0, 2> xxz;
            detail::shuffle_accessor_4<vec3, 1, 0, 2> yxz;
            detail::shuffle_accessor_4<vec3, 2, 0, 2> zxz;
            detail::shuffle_accessor_4<vec3, 3, 0, 2> wxz;
            detail::shuffle_accessor_4<vec3, 0, 1, 2> xyz;
            detail::shuffle_accessor_4<vec3, 1, 1, 2> yyz;
            detail::shuffle_accessor_4<vec3, 2, 1, 2> zyz;
            detail::shuffle_accessor_4<vec3, 3, 1, 2> wyz;
            detail::shuffle_accessor_4<vec3, 0, 2, 2> xzz;
            detail::shuffle_accessor_4<vec3, 1, 2, 2> yzz;
            detail::shuffle_accessor_4<vec3, 2, 2, 2> zzz;
            detail::shuffle_accessor_4<vec3, 3, 2, 2> wzz;
            detail::shuffle_accessor_4<vec3, 0, 3, 2> xwz;
            detail::shuffle_accessor_4<vec3, 1, 3, 2> ywz;
            detail::shuffle_accessor_4<vec3, 2, 3, 2> zwz;
            detail::shuffle_accessor_4<vec3, 3, 3, 2> wwz;
            detail::shuffle_accessor_4<vec3, 0, 0, 3> xxw;
            detail::shuffle_accessor_4<vec3, 1, 0, 3> yxw;
            detail::shuffle_accessor_4<vec3, 2, 0, 3> zxw;
            detail::shuffle_accessor_4<vec3, 3, 0, 3> wxw;
            detail::shuffle_accessor_4<vec3, 0, 1, 3> xyw;
            detail::shuffle_accessor_4<vec3, 1, 1, 3> yyw;
            detail::shuffle_accessor_4<vec3, 2, 1, 3> zyw;
            detail::shuffle_accessor_4<vec3, 3, 1, 3> wyw;
            detail::shuffle_accessor_4<vec3, 0, 2, 3> xzw;
            detail::shuffle_accessor_4<vec3, 1, 2, 3> yzw;
            detail::shuffle_accessor_4<vec3, 2, 2, 3> zzw;
            detail::shuffle_accessor_4<vec3, 3, 2, 3> wzw;
            detail::shuffle_accessor_4<vec3, 0, 3, 3> xww;
            detail::shuffle_accessor_4<vec3, 1, 3, 3> yww;
            detail::shuffle_accessor_4<vec3, 2, 3, 3> zww;
            detail::shuffle_accessor_4<vec3, 3, 3, 3> www;

            detail::shuffle_accessor_4<vec4, 0, 0, 0, 0> xxxx;
            detail::shuffle_accessor_4<vec4, 1, 0, 0, 0> yxxx;
            detail::shuffle_accessor_4<vec4, 2, 0, 0, 0> zxxx;
            detail::shuffle_accessor_4<vec4, 3, 0, 0, 0> wxxx;
            detail::shuffle_accessor_4<vec4, 0, 1, 0, 0> xyxx;
            detail::shuffle_accessor_4<vec4, 1, 1, 0, 0> yyxx;
            detail::shuffle_accessor_4<vec4, 2, 1, 0, 0> zyxx;
            detail::shuffle_accessor_4<vec4, 3, 1, 0, 0> wyxx;
            detail::shuffle_accessor_4<vec4, 0, 2, 0, 0> xzxx;
            detail::shuffle_accessor_4<vec4, 1, 2, 0, 0> yzxx;
            detail::shuffle_accessor_4<vec4, 2, 2, 0, 0> zzxx;
            detail::shuffle_accessor_4<vec4, 3, 2, 0, 0> wzxx;
            detail::shuffle_accessor_4<vec4, 0, 3, 0, 0> xwxx;
            detail::shuffle_accessor_4<vec4, 1, 3, 0, 0> ywxx;
            detail::shuffle_accessor_4<vec4, 2, 3, 0, 0> zwxx;
            detail::shuffle_accessor_4<vec4, 3, 3, 0, 0> wwxx;
            detail::shuffle_accessor_4<vec4, 0, 0, 1, 0> xxyx;
            detail::shuffle_accessor_4<vec4, 1, 0, 1, 0> yxyx;
            detail::shuffle_accessor_4<vec4, 2, 0, 1, 0> zxyx;
            detail::shuffle_accessor_4<vec4, 3, 0, 1, 0> wxyx;
            detail::shuffle_accessor_4<vec4, 0, 1, 1, 0> xyyx;
            detail::shuffle_accessor_4<vec4, 1, 1, 1, 0> yyyx;
            detail::shuffle_accessor_4<vec4, 2, 1, 1, 0> zyyx;
            detail::shuffle_accessor_4<vec4, 3, 1, 1, 0> wyyx;
            detail::shuffle_accessor_4<vec4, 0, 2, 1, 0> xzyx;
            detail::shuffle_accessor_4<vec4, 1, 2, 1, 0> yzyx;
            detail::shuffle_accessor_4<vec4, 2, 2, 1, 0> zzyx;
            detail::shuffle_accessor_4<vec4, 3, 2, 1, 0> wzyx;
            detail::shuffle_accessor_4<vec4, 0, 3, 1, 0> xwyx;
            detail::shuffle_accessor_4<vec4, 1, 3, 1, 0> ywyx;
            detail::shuffle_accessor_4<vec4, 2, 3, 1, 0> zwyx;
            detail::shuffle_accessor_4<vec4, 3, 3, 1, 0> wwyx;
            detail::shuffle_accessor_4<vec4, 0, 0, 2, 0> xxzx;
            detail::shuffle_accessor_4<vec4, 1, 0, 2, 0> yxzx;
            detail::shuffle_accessor_4<vec4, 2, 0, 2, 0> zxzx;
            detail::shuffle_accessor_4<vec4, 3, 0, 2, 0> wxzx;
            detail::shuffle_accessor_4<vec4, 0, 1, 2, 0> xyzx;
            detail::shuffle_accessor_4<vec4, 1, 1, 2, 0> yyzx;
            detail::shuffle_accessor_4<vec4, 2, 1, 2, 0> zyzx;
            detail::shuffle_accessor_4<vec4, 3, 1, 2, 0> wyzx;
            detail::shuffle_accessor_4<vec4, 0, 2, 2, 0> xzzx;
            detail::shuffle_accessor_4<vec4, 1, 2, 2, 0> yzzx;
            detail::shuffle_accessor_4<vec4, 2, 2, 2, 0> zzzx;
            detail::shuffle_accessor_4<vec4, 3, 2, 2, 0> wzzx;
            detail::shuffle_accessor_4<vec4, 0, 3, 2, 0> xwzx;
            detail::shuffle_accessor_4<vec4, 1, 3, 2, 0> ywzx;
            detail::shuffle_accessor_4<vec4, 2, 3, 2, 0> zwzx;
            detail::shuffle_accessor_4<vec4, 3, 3, 2, 0> wwzx;
            detail::shuffle_accessor_4<vec4, 0, 0, 3, 0> xxwx;
            detail::shuffle_accessor_4<vec4, 1, 0, 3, 0> yxwx;
            detail::shuffle_accessor_4<vec4, 2, 0, 3, 0> zxwx;
            detail::shuffle_accessor_4<vec4, 3, 0, 3, 0> wxwx;
            detail::shuffle_accessor_4<vec4, 0, 1, 3, 0> xywx;
            detail::shuffle_accessor_4<vec4, 1, 1, 3, 0> yywx;
            detail::shuffle_accessor_4<vec4, 2, 1, 3, 0> zywx;
            detail::shuffle_accessor_4<vec4, 3, 1, 3, 0> wywx;
            detail::shuffle_accessor_4<vec4, 0, 2, 3, 0> xzwx;
            detail::shuffle_accessor_4<vec4, 1, 2, 3, 0> yzwx;
            detail::shuffle_accessor_4<vec4, 2, 2, 3, 0> zzwx;
            detail::shuffle_accessor_4<vec4, 3, 2, 3, 0> wzwx;
            detail::shuffle_accessor_4<vec4, 0, 3, 3, 0> xwwx;
            detail::shuffle_accessor_4<vec4, 1, 3, 3, 0> ywwx;
            detail::shuffle_accessor_4<vec4, 2, 3, 3, 0> zwwx;
            detail::shuffle_accessor_4<vec4, 3, 3, 3, 0> wwwx;
            detail::shuffle_accessor_4<vec4, 0, 0, 0, 1> xxxy;
            detail::shuffle_accessor_4<vec4, 1, 0, 0, 1> yxxy;
            detail::shuffle_accessor_4<vec4, 2, 0, 0, 1> zxxy;
            detail::shuffle_accessor_4<vec4, 3, 0, 0, 1> wxxy;
            detail::shuffle_accessor_4<vec4, 0, 1, 0, 1> xyxy;
            detail::shuffle_accessor_4<vec4, 1, 1, 0, 1> yyxy;
            detail::shuffle_accessor_4<vec4, 2, 1, 0, 1> zyxy;
            detail::shuffle_accessor_4<vec4, 3, 1, 0, 1> wyxy;
            detail::shuffle_accessor_4<vec4, 0, 2, 0, 1> xzxy;
            detail::shuffle_accessor_4<vec4, 1, 2, 0, 1> yzxy;
            detail::shuffle_accessor_4<vec4, 2, 2, 0, 1> zzxy;
            detail::shuffle_accessor_4<vec4, 3, 2, 0, 1> wzxy;
            detail::shuffle_accessor_4<vec4, 0, 3, 0, 1> xwxy;
            detail::shuffle_accessor_4<vec4, 1, 3, 0, 1> ywxy;
            detail::shuffle_accessor_4<vec4, 2, 3, 0, 1> zwxy;
            detail::shuffle_accessor_4<vec4, 3, 3, 0, 1> wwxy;
            detail::shuffle_accessor_4<vec4, 0, 0, 1, 1> xxyy;
            detail::shuffle_accessor_4<vec4, 1, 0, 1, 1> yxyy;
            detail::shuffle_accessor_4<vec4, 2, 0, 1, 1> zxyy;
            detail::shuffle_accessor_4<vec4, 3, 0, 1, 1> wxyy;
            detail::shuffle_accessor_4<vec4, 0, 1, 1, 1> xyyy;
            detail::shuffle_accessor_4<vec4, 1, 1, 1, 1> yyyy;
            detail::shuffle_accessor_4<vec4, 2, 1, 1, 1> zyyy;
            detail::shuffle_accessor_4<vec4, 3, 1, 1, 1> wyyy;
            detail::shuffle_accessor_4<vec4, 0, 2, 1, 1> xzyy;
            detail::shuffle_accessor_4<vec4, 1, 2, 1, 1> yzyy;
            detail::shuffle_accessor_4<vec4, 2, 2, 1, 1> zzyy;
            detail::shuffle_accessor_4<vec4, 3, 2, 1, 1> wzyy;
            detail::shuffle_accessor_4<vec4, 0, 3, 1, 1> xwyy;
            detail::shuffle_accessor_4<vec4, 1, 3, 1, 1> ywyy;
            detail::shuffle_accessor_4<vec4, 2, 3, 1, 1> zwyy;
            detail::shuffle_accessor_4<vec4, 3, 3, 1, 1> wwyy;
            detail::shuffle_accessor_4<vec4, 0, 0, 2, 1> xxzy;
            detail::shuffle_accessor_4<vec4, 1, 0, 2, 1> yxzy;
            detail::shuffle_accessor_4<vec4, 2, 0, 2, 1> zxzy;
            detail::shuffle_accessor_4<vec4, 3, 0, 2, 1> wxzy;
            detail::shuffle_accessor_4<vec4, 0, 1, 2, 1> xyzy;
            detail::shuffle_accessor_4<vec4, 1, 1, 2, 1> yyzy;
            detail::shuffle_accessor_4<vec4, 2, 1, 2, 1> zyzy;
            detail::shuffle_accessor_4<vec4, 3, 1, 2, 1> wyzy;
            detail::shuffle_accessor_4<vec4, 0, 2, 2, 1> xzzy;
            detail::shuffle_accessor_4<vec4, 1, 2, 2, 1> yzzy;
            detail::shuffle_accessor_4<vec4, 2, 2, 2, 1> zzzy;
            detail::shuffle_accessor_4<vec4, 3, 2, 2, 1> wzzy;
            detail::shuffle_accessor_4<vec4, 0, 3, 2, 1> xwzy;
            detail::shuffle_accessor_4<vec4, 1, 3, 2, 1> ywzy;
            detail::shuffle_accessor_4<vec4, 2, 3, 2, 1> zwzy;
            detail::shuffle_accessor_4<vec4, 3, 3, 2, 1> wwzy;
            detail::shuffle_accessor_4<vec4, 0, 0, 3, 1> xxwy;
            detail::shuffle_accessor_4<vec4, 1, 0, 3, 1> yxwy;
            detail::shuffle_accessor_4<vec4, 2, 0, 3, 1> zxwy;
            detail::shuffle_accessor_4<vec4, 3, 0, 3, 1> wxwy;
            detail::shuffle_accessor_4<vec4, 0, 1, 3, 1> xywy;
            detail::shuffle_accessor_4<vec4, 1, 1, 3, 1> yywy;
            detail::shuffle_accessor_4<vec4, 2, 1, 3, 1> zywy;
            detail::shuffle_accessor_4<vec4, 3, 1, 3, 1> wywy;
            detail::shuffle_accessor_4<vec4, 0, 2, 3, 1> xzwy;
            detail::shuffle_accessor_4<vec4, 1, 2, 3, 1> yzwy;
            detail::shuffle_accessor_4<vec4, 2, 2, 3, 1> zzwy;
            detail::shuffle_accessor_4<vec4, 3, 2, 3, 1> wzwy;
            detail::shuffle_accessor_4<vec4, 0, 3, 3, 1> xwwy;
            detail::shuffle_accessor_4<vec4, 1, 3, 3, 1> ywwy;
            detail::shuffle_accessor_4<vec4, 2, 3, 3, 1> zwwy;
            detail::shuffle_accessor_4<vec4, 3, 3, 3, 1> wwwy;
            detail::shuffle_accessor_4<vec4, 0, 0, 0, 2> xxxz;
            detail::shuffle_accessor_4<vec4, 1, 0, 0, 2> yxxz;
            detail::shuffle_accessor_4<vec4, 2, 0, 0, 2> zxxz;
            detail::shuffle_accessor_4<vec4, 3, 0, 0, 2> wxxz;
            detail::shuffle_accessor_4<vec4, 0, 1, 0, 2> xyxz;
            detail::shuffle_accessor_4<vec4, 1, 1, 0, 2> yyxz;
            detail::shuffle_accessor_4<vec4, 2, 1, 0, 2> zyxz;
            detail::shuffle_accessor_4<vec4, 3, 1, 0, 2> wyxz;
            detail::shuffle_accessor_4<vec4, 0, 2, 0, 2> xzxz;
            detail::shuffle_accessor_4<vec4, 1, 2, 0, 2> yzxz;
            detail::shuffle_accessor_4<vec4, 2, 2, 0, 2> zzxz;
            detail::shuffle_accessor_4<vec4, 3, 2, 0, 2> wzxz;
            detail::shuffle_accessor_4<vec4, 0, 3, 0, 2> xwxz;
            detail::shuffle_accessor_4<vec4, 1, 3, 0, 2> ywxz;
            detail::shuffle_accessor_4<vec4, 2, 3, 0, 2> zwxz;
            detail::shuffle_accessor_4<vec4, 3, 3, 0, 2> wwxz;
            detail::shuffle_accessor_4<vec4, 0, 0, 1, 2> xxyz;
            detail::shuffle_accessor_4<vec4, 1, 0, 1, 2> yxyz;
            detail::shuffle_accessor_4<vec4, 2, 0, 1, 2> zxyz;
            detail::shuffle_accessor_4<vec4, 3, 0, 1, 2> wxyz;
            detail::shuffle_accessor_4<vec4, 0, 1, 1, 2> xyyz;
            detail::shuffle_accessor_4<vec4, 1, 1, 1, 2> yyyz;
            detail::shuffle_accessor_4<vec4, 2, 1, 1, 2> zyyz;
            detail::shuffle_accessor_4<vec4, 3, 1, 1, 2> wyyz;
            detail::shuffle_accessor_4<vec4, 0, 2, 1, 2> xzyz;
            detail::shuffle_accessor_4<vec4, 1, 2, 1, 2> yzyz;
            detail::shuffle_accessor_4<vec4, 2, 2, 1, 2> zzyz;
            detail::shuffle_accessor_4<vec4, 3, 2, 1, 2> wzyz;
            detail::shuffle_accessor_4<vec4, 0, 3, 1, 2> xwyz;
            detail::shuffle_accessor_4<vec4, 1, 3, 1, 2> ywyz;
            detail::shuffle_accessor_4<vec4, 2, 3, 1, 2> zwyz;
            detail::shuffle_accessor_4<vec4, 3, 3, 1, 2> wwyz;
            detail::shuffle_accessor_4<vec4, 0, 0, 2, 2> xxzz;
            detail::shuffle_accessor_4<vec4, 1, 0, 2, 2> yxzz;
            detail::shuffle_accessor_4<vec4, 2, 0, 2, 2> zxzz;
            detail::shuffle_accessor_4<vec4, 3, 0, 2, 2> wxzz;
            detail::shuffle_accessor_4<vec4, 0, 1, 2, 2> xyzz;
            detail::shuffle_accessor_4<vec4, 1, 1, 2, 2> yyzz;
            detail::shuffle_accessor_4<vec4, 2, 1, 2, 2> zyzz;
            detail::shuffle_accessor_4<vec4, 3, 1, 2, 2> wyzz;
            detail::shuffle_accessor_4<vec4, 0, 2, 2, 2> xzzz;
            detail::shuffle_accessor_4<vec4, 1, 2, 2, 2> yzzz;
            detail::shuffle_accessor_4<vec4, 2, 2, 2, 2> zzzz;
            detail::shuffle_accessor_4<vec4, 3, 2, 2, 2> wzzz;
            detail::shuffle_accessor_4<vec4, 0, 3, 2, 2> xwzz;
            detail::shuffle_accessor_4<vec4, 1, 3, 2, 2> ywzz;
            detail::shuffle_accessor_4<vec4, 2, 3, 2, 2> zwzz;
            detail::shuffle_accessor_4<vec4, 3, 3, 2, 2> wwzz;
            detail::shuffle_accessor_4<vec4, 0, 0, 3, 2> xxwz;
            detail::shuffle_accessor_4<vec4, 1, 0, 3, 2> yxwz;
            detail::shuffle_accessor_4<vec4, 2, 0, 3, 2> zxwz;
            detail::shuffle_accessor_4<vec4, 3, 0, 3, 2> wxwz;
            detail::shuffle_accessor_4<vec4, 0, 1, 3, 2> xywz;
            detail::shuffle_accessor_4<vec4, 1, 1, 3, 2> yywz;
            detail::shuffle_accessor_4<vec4, 2, 1, 3, 2> zywz;
            detail::shuffle_accessor_4<vec4, 3, 1, 3, 2> wywz;
            detail::shuffle_accessor_4<vec4, 0, 2, 3, 2> xzwz;
            detail::shuffle_accessor_4<vec4, 1, 2, 3, 2> yzwz;
            detail::shuffle_accessor_4<vec4, 2, 2, 3, 2> zzwz;
            detail::shuffle_accessor_4<vec4, 3, 2, 3, 2> wzwz;
            detail::shuffle_accessor_4<vec4, 0, 3, 3, 2> xwwz;
            detail::shuffle_accessor_4<vec4, 1, 3, 3, 2> ywwz;
            detail::shuffle_accessor_4<vec4, 2, 3, 3, 2> zwwz;
            detail::shuffle_accessor_4<vec4, 3, 3, 3, 2> wwwz;
            detail::shuffle_accessor_4<vec4, 0, 0, 0, 3> xxxw;
            detail::shuffle_accessor_4<vec4, 1, 0, 0, 3> yxxw;
            detail::shuffle_accessor_4<vec4, 2, 0, 0, 3> zxxw;
            detail::shuffle_accessor_4<vec4, 3, 0, 0, 3> wxxw;
            detail::shuffle_accessor_4<vec4, 0, 1, 0, 3> xyxw;
            detail::shuffle_accessor_4<vec4, 1, 1, 0, 3> yyxw;
            detail::shuffle_accessor_4<vec4, 2, 1, 0, 3> zyxw;
            detail::shuffle_accessor_4<vec4, 3, 1, 0, 3> wyxw;
            detail::shuffle_accessor_4<vec4, 0, 2, 0, 3> xzxw;
            detail::shuffle_accessor_4<vec4, 1, 2, 0, 3> yzxw;
            detail::shuffle_accessor_4<vec4, 2, 2, 0, 3> zzxw;
            detail::shuffle_accessor_4<vec4, 3, 2, 0, 3> wzxw;
            detail::shuffle_accessor_4<vec4, 0, 3, 0, 3> xwxw;
            detail::shuffle_accessor_4<vec4, 1, 3, 0, 3> ywxw;
            detail::shuffle_accessor_4<vec4, 2, 3, 0, 3> zwxw;
            detail::shuffle_accessor_4<vec4, 3, 3, 0, 3> wwxw;
            detail::shuffle_accessor_4<vec4, 0, 0, 1, 3> xxyw;
            detail::shuffle_accessor_4<vec4, 1, 0, 1, 3> yxyw;
            detail::shuffle_accessor_4<vec4, 2, 0, 1, 3> zxyw;
            detail::shuffle_accessor_4<vec4, 3, 0, 1, 3> wxyw;
            detail::shuffle_accessor_4<vec4, 0, 1, 1, 3> xyyw;
            detail::shuffle_accessor_4<vec4, 1, 1, 1, 3> yyyw;
            detail::shuffle_accessor_4<vec4, 2, 1, 1, 3> zyyw;
            detail::shuffle_accessor_4<vec4, 3, 1, 1, 3> wyyw;
            detail::shuffle_accessor_4<vec4, 0, 2, 1, 3> xzyw;
            detail::shuffle_accessor_4<vec4, 1, 2, 1, 3> yzyw;
            detail::shuffle_accessor_4<vec4, 2, 2, 1, 3> zzyw;
            detail::shuffle_accessor_4<vec4, 3, 2, 1, 3> wzyw;
            detail::shuffle_accessor_4<vec4, 0, 3, 1, 3> xwyw;
            detail::shuffle_accessor_4<vec4, 1, 3, 1, 3> ywyw;
            detail::shuffle_accessor_4<vec4, 2, 3, 1, 3> zwyw;
            detail::shuffle_accessor_4<vec4, 3, 3, 1, 3> wwyw;
            detail::shuffle_accessor_4<vec4, 0, 0, 2, 3> xxzw;
            detail::shuffle_accessor_4<vec4, 1, 0, 2, 3> yxzw;
            detail::shuffle_accessor_4<vec4, 2, 0, 2, 3> zxzw;
            detail::shuffle_accessor_4<vec4, 3, 0, 2, 3> wxzw;
            detail::shuffle_accessor_4<vec4, 0, 1, 2, 3> xyzw;
            detail::shuffle_accessor_4<vec4, 1, 1, 2, 3> yyzw;
            detail::shuffle_accessor_4<vec4, 2, 1, 2, 3> zyzw;
            detail::shuffle_accessor_4<vec4, 3, 1, 2, 3> wyzw;
            detail::shuffle_accessor_4<vec4, 0, 2, 2, 3> xzzw;
            detail::shuffle_accessor_4<vec4, 1, 2, 2, 3> yzzw;
            detail::shuffle_accessor_4<vec4, 2, 2, 2, 3> zzzw;
            detail::shuffle_accessor_4<vec4, 3, 2, 2, 3> wzzw;
            detail::shuffle_accessor_4<vec4, 0, 3, 2, 3> xwzw;
            detail::shuffle_accessor_4<vec4, 1, 3, 2, 3> ywzw;
            detail::shuffle_accessor_4<vec4, 2, 3, 2, 3> zwzw;
            detail::shuffle_accessor_4<vec4, 3, 3, 2, 3> wwzw;
            detail::shuffle_accessor_4<vec4, 0, 0, 3, 3> xxww;
            detail::shuffle_accessor_4<vec4, 1, 0, 3, 3> yxww;
            detail::shuffle_accessor_4<vec4, 2, 0, 3, 3> zxww;
            detail::shuffle_accessor_4<vec4, 3, 0, 3, 3> wxww;
            detail::shuffle_accessor_4<vec4, 0, 1, 3, 3> xyww;
            detail::shuffle_accessor_4<vec4, 1, 1, 3, 3> yyww;
            detail::shuffle_accessor_4<vec4, 2, 1, 3, 3> zyww;
            detail::shuffle_accessor_4<vec4, 3, 1, 3, 3> wyww;
            detail::shuffle_accessor_4<vec4, 0, 2, 3, 3> xzww;
            detail::shuffle_accessor_4<vec4, 1, 2, 3, 3> yzww;
            detail::shuffle_accessor_4<vec4, 2, 2, 3, 3> zzww;
            detail::shuffle_accessor_4<vec4, 3, 2, 3, 3> wzww;
            detail::shuffle_accessor_4<vec4, 0, 3, 3, 3> xwww;
            detail::shuffle_accessor_4<vec4, 1, 3, 3, 3> ywww;
            detail::shuffle_accessor_4<vec4, 2, 3, 3, 3> zwww;
            detail::shuffle_accessor_4<vec4, 3, 3, 3, 3> wwww;
        };
    };

    bool operator==(const vec4& first, const vec4& second) noexcept;
    bool operator!=(const vec4& first, const vec4& second) noexcept;

    vec4 operator -(const vec4& first) noexcept;
    vec4 operator +(const vec4& first) noexcept;

    vec4 operator +(const vec4& first, const vec4& second) noexcept;
    vec4 operator -(const vec4& first, const vec4& second) noexcept;
    vec4 operator *(const vec4& first, const vec4& second) noexcept;
    vec4 operator /(const vec4& first, const vec4& second) noexcept;

    vec4 operator *(const vec4& vec, const float scalar) noexcept;
    vec4 operator /(const vec4& vec, const float scalar) noexcept;

    vec4 operator *(const float scalar, const vec4& vec) noexcept;
    vec4 operator /(const float scalar, const vec4& vec) noexcept;

}
